### ISSUE TITLE
Localize this extension using the Localization pipeline

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-gather#109]
Everything you need to know is here :) https://github.com/microsoft/vscode-engineering/wiki/Extensions-Localization

**Comment by DonJayamanne** [comment]
Closing as not planned

**Comment by TylerLeonhardt** [comment]
@DonJayamanne is this extension being deprecated? Or is it a sample? If not we should keep this open because every extension should be localized as best we can

**Comment by DonJayamanne** [comment]
plan is to deprecate
