### ISSUE TITLE
gathering into a script returns only one cell

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-gather#23]
-check if that was the case before and if so
-return the script with cell markers

Here's the input:
First cell:
# %% Basic Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
    
Second cell:    
# %% Matplotlib Plot
x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()
    
I get one cell when gathering  
Result: 
# %%
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 20, 100)
plt.plot(x, np.sin(x))
plt.show()

**Comment by DonJayamanne** [comment]
Closing as not planned
