### ISSUE TITLE
Gather button appears and does nothing when kernel autostart is off

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-gather#24]
With autostart turned off when a notebook is initially opened the gather buttons are available and look enabled, but have no tooltip and nothing happens when you click them:

![image](https://user-images.githubusercontent.com/20347396/98606591-5c142a00-229c-11eb-88e9-625da380d3da.png)

**Comment by DonJayamanne** [comment]
Closing as not planned
