### ISSUE TITLE
Gathered notebook is not dirty

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-gather#25]
When you gather to a notebook, the notebook is not dirty, so you have to change it to actually save it (the save button is disabled) no need to fix now I think, but might be a nice QOL fix to be able to hit the save button after gathering.

![image](https://user-images.githubusercontent.com/20347396/98606977-1146e200-229d-11eb-9f24-5c6dc77531fa.png)

**Comment by DonJayamanne** [comment]
Closing as not planned
