### ISSUE TITLE
Gather is analyzing variable fetching operations

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode-gather#35]
![image](https://user-images.githubusercontent.com/812783/98712785-95e83d80-233b-11eb-9a83-8e155919a5d7.png)

The %who_ls command here is the python variable fetching operation, not something that I've run. So looks like we might need to ignore silent executions.

**Comment by DavidKutu** [comment]
Solved in the jupyter extension
https://github.com/microsoft/vscode-jupyter/blob/9fda0a9357010df67cbdde723084e33be919f259/src/client/datascience/notebookExtensibility.ts#L32
