### ISSUE TITLE
Gather not working together with the remote case in the AML extension

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-gather#38]
**Steps to reproduce**
1. Run all cells in 'PetDetectorTraining.ipynb' in this repo (https://github.com/jmew/pet-detector-pytorch) on a remote machine using the AML extension.

1. Press gather on the last cell

**Expected Result**
Get appropiate code

**Actual Result**
Gather returns a single line of code

**Comment by DonJayamanne** [comment]
Closing as not planned
