### ISSUE TITLE
Tooltip ignoring "Gather To Script" setting

### ISSUE THREAD

**Issue by pascalbleuler** [microsoft/vscode-gather#39]
Hi all,

When `"gather.gatherToScript": true`, I would expect the tooltip of the "Gather" button above cells in notebooks to reflect the setting. Instead, the tooltip shows
```
"Gather the code required to generate this cell
into a new notebook"
```
regardless of the setting.

Screenshot to illustrate:
<img width="1355" alt="Screenshot 2020-12-02 at 19 16 58" src="https://user-images.githubusercontent.com/59290596/100915482-b6d42680-34d4-11eb-8219-2e190ede6462.png">

**Comment by DavidKutu** [comment]
Thanks for the issue @pascalbleuler. Since the tooltip (the whole button really) gets passed around once, and the setting might change later, we'll probably just change the tooltip to be more accurate.
