### ISSUE TITLE
After a while, gather only returns the cell that is being gathered

### ISSUE THREAD

**Issue by DavidKutu** [microsoft/vscode-gather#42]
Its possible to get to a state where you click the gather button and all you get is the code from the cell you're gathering (actually may just be a single line).

We're still looking for a consistent repro.

**Comment by DavidKutu** [comment]
Possible repro:

1. Run a whole notebook, a big one that reads a csv
1. Open a new csv and play around with the data to build a new dataframe.
1. Gather the dataframe when done. It should have the imports, the read_csv, and any other related manipulations to get to the same state of the dataframe.

**Comment by DonJayamanne** [comment]
Closing as not planned
