### ISSUE TITLE
Gather generates empty notebook

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode-gather#47]
Originally reported here: https://github.com/microsoft/vscode-jupyter/issues/1209

In the following notebook, when I gather the second cell, I'd expect the definition from cell 1 and the use from cell 2 to be present in the gathered notebook. However, Gather generates an empty notebook.

![image](https://user-images.githubusercontent.com/30305945/104410165-a4f69200-551c-11eb-81c8-d34d71b457fd.png)

**Comment by DonJayamanne** [comment]
Closing as not planned
