### ISSUE TITLE
Gather still showing up on non-python notebooks

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-gather#57]
TypeScript notebook showing gather in cell toolbar

![image](https://user-images.githubusercontent.com/19276747/111923273-93b98c80-8a5b-11eb-927f-36e78162a552.png)

**Comment by DonJayamanne** [comment]
Fyi, this upcoming will probably show up in .net, julia , r notebooks and other non python notebooks.

**Comment by DonJayamanne** [comment]
Closing as not planned
