### ISSUE TITLE
Gather + Multiselect 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-gather#59]
Suggestion: 
If multiselect is enabled and a user Gathers on multiple cells, it could behave like below. 

Example: 
A depends on cell 2*, B depends on cell 2* and 5*. 
Gather with order maintained and remove duplicates if a line of code contributes to both Gathered cells. 
![image](https://user-images.githubusercontent.com/19276747/112359202-43764080-8c8e-11eb-8f4d-db8439395fe9.png)

**Comment by DonJayamanne** [comment]
Closing as not planned
