### ISSUE TITLE
"Exception at Activate" error for "Gather" extension, not sure how to resolve?

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode-gather#71]
## Environment data

-   VS Code version: 1.60.0
-   Jupyter Extension version (available under the Extensions sidebar): v2021.8.2031190714
-   Python Extension version (available under the Extensions sidebar): v2021.9.1191016588
-   OS (Windows | Mac | Linux distro) and version: macOS 11.5.2
-   Python and/or Anaconda version: 3.9.6
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): virtualenv (via Poetry)
-   Jupyter server running: N/A? (I'm not sure, more details below)

## Problem statement

I'm opening this issue here because that's where the error I encountered pointed me to

When launching a Python project that is using Poetry to manage dependencies (honestly not sure if this is applicable, but I only use Poetry projects these days), I get an error at the bottom left that says `Gather: Exception at Activate Please reload VS Voce`:

<img width="473" alt="CleanShot Code 2021-09-02 at 20 15 32" src="https://user-images.githubusercontent.com/8128941/131931683-c3550c9b-601f-418f-9a3e-10c8a6204337.png">

I reload VS Code, restart, etc., and it doesn't seem to make this error go away. Is there a way to look at more detail about the error that's being encountered? I don't really understand what "Gather" is, and there's no direction in the pop-up to let the user (me) look for additional logging about what's wrong.

I can reproduce this reliably even when I disable all extensions and just enable this Gather extension manually (after enabling Python/Jupyter - Python/Jupyter seem to enable fine though).

**Comment by macintacos** [comment]
Fair @greazer 🙂! I don't even really remember why I installed it, I think I remember just reading the description and being intrigued by it since I was experimenting more and more with Jupyter at the time. If it's okay to uninstall I can go ahead and do that - hope that this bug report is useful though.

**Comment by priyanka01deb** [comment]
Facing the same issue. Any workaround?

**Comment by DavidKutu** [comment]
@priyanka01deb We'll have a new release that'll fix this soon.

**Comment by DavidKutu** [comment]
@priyanka01deb, the new release is out :)
