### ISSUE TITLE
Gather takes over a second to activate

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode-gather#76]
1. Install the Gather extension
2. Open a notebook (ipynb)
3. Run the ```Developer: Show Running Extensions```

Most other extensions are under 300ms, including Python and Jupyter. 

![image](https://user-images.githubusercontent.com/11685408/134252992-24bcb1aa-c446-486b-a761-672b0b0d1492.png)

**Comment by DonJayamanne** [comment]
Closing as not planned
